version: '3.9'

networks:
  droidnet:
    driver: bridge

volumes:
  adb_keys:
  playflow_data:

services:
  controller:
    build: .
    container_name: droid_controller
    privileged: true
    networks: [droidnet]
    environment:
      - ADB_SERVER_SOCKET=tcp:5037
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - adb_keys:/root/.android
      - ./templates:/opt/dcluster/templates:ro
      - ./scripts:/opt/dcluster/scripts:ro
    healthcheck:
      test: ["CMD-SHELL","adb start-server >/dev/null 2>&1 && adb devices | grep -q 'List of devices'"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  emulator:
    image: budtmo/docker-android-x86-13.0
    container_name: droid_emulator
    privileged: true
    networks: [droidnet]
    environment:
      - DEVICE=Samsung Galaxy S10
      - EMULATOR_PARAMS=-noaudio -gpu swiftshader_indirect
      - APPIUM=false
      - CONNECT_TO_GRID=false
    ports:
      - "6080:6080"   # noVNC
      - "5555:5555"   # adbd
    healthcheck:
      test: ["CMD-SHELL","nc -z localhost 5555 && nc -z localhost 6080"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  playflow:
    build:
      context: ./playflow
      dockerfile: Dockerfile
    container_name: droid_playflow
    networks: [droidnet]
    depends_on:
      controller:
        condition: service_healthy
    environment:
      - ADB_SERVER_SOCKET=tcp:controller:5037
      - DEVICE_SERIAL=
    volumes:
      - playflow_data:/var/lib/playflow
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:5000/health || exit 1"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12