version: '3.9'

networks:
  droidnet:
    driver: bridge

volumes:
  adb_keys:
  playflow_data:

services:
  controller:
    build: .
    container_name: droid_controller
    profiles: [usb]
    privileged: true
    networks:
      droidnet:
        aliases: [controller]
    environment:
      - ADB_SERVER_SOCKET=${ADB_SERVER_SOCKET:-tcp:5037}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - adb_keys:/root/.android
      - ./templates:/opt/dcluster/templates:ro
      - ./templates/udev-rules.d:/etc/udev/rules.d:ro
      - ./scripts:/opt/dcluster/scripts:ro
    entrypoint: ["/bin/bash","-lc","/opt/dcluster/scripts/controller-entrypoint.sh"]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL","adb start-server >/dev/null 2>&1 && adb devices | grep -q 'List of devices'"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  emulator:
    image: budtmo/docker-android-x86-13.0
    container_name: droid_emulator
    privileged: true
    profiles: [emulator]
    networks: [droidnet]
    environment:
      - DEVICE=${DEVICE:-Samsung Galaxy S10}
      - EMULATOR_PARAMS=${EMULATOR_PARAMS:--noaudio -gpu swiftshader_indirect}
      - APPIUM=false
      - CONNECT_TO_GRID=false
    ports:
      - "6080:6080"
      - "5555:5555"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL","bash -lc 'exec 3<>/dev/tcp/127.0.0.1/5555 && exec 3>&-; exec 3<&-; exit 0' && curl -fsS http://127.0.0.1:6080 >/dev/null"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  playflow:
    build:
      context: ./playflow
      dockerfile: Dockerfile
    container_name: droid_playflow
    profiles: [emulator]
    networks: [droidnet]
    depends_on:
      controller:
        condition: service_healthy
    environment:
      - ADB_SERVER_SOCKET=${ADB_SERVER_SOCKET:-tcp:controller:5037}
      - DEVICE_SERIAL=${DEVICE_SERIAL:-}
    volumes:
      - playflow_data:/var/lib/playflow
    ports:
      - "${PLAYFLOW_PORT:-5000}:5000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:5000/health || exit 1"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12