volumes:
  playflow_data:

services:
  pf_emulator:
    image: halimqarroum/docker-android:api-33-playstore
    container_name: pf_emulator
    shm_size: "2g"
    privileged: true
    devices:
      - "/dev/kvm:/dev/kvm"
    environment:
      - DEVICE=${DEVICE:-Pixel_6}
      - EMULATOR_PARAMS=${EMULATOR_PARAMS:--noaudio -gpu swiftshader_indirect -no-boot-anim -wipe-data}
      - WEB_VNC=${WEB_VNC:-false}
    healthcheck:
      test:
        - CMD-SHELL
        - |
          set -e
          adb start-server >/dev/null 2>&1 || true
          adb wait-for-device
          adb shell getprop sys.boot_completed 2>/dev/null | grep -q 1
      start_period: 120s
      interval: 15s
      timeout: 10s
      retries: 20

  pf_droidflow:
    build:
      context: .
      dockerfile: playflow/Dockerfile
    container_name: pf_droidflow
    environment:
      - PLAYFLOW_PORT=${PLAYFLOW_PORT:-5000}
      - DEVICE_SERIAL=${DEVICE_SERIAL:-}
      - ANDROID_MODE=${ANDROID_MODE:-emulator}
      - EMULATOR_HOST=${EMULATOR_HOST:-pf_emulator}
      - EMULATOR_PORT=${EMULATOR_PORT:-5555}
    volumes:
      - playflow_data:/var/lib/playflow
    ports:
      - "${PLAYFLOW_PORT:-5000}:5000"
    tmpfs:
      - /tmp
    depends_on:
      - pf_emulator
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12