version: "3.8"

volumes:
  playflow_data:

services:
  pf_emulator:
    image: halimqarroum/docker-android:api-33-playstore
    container_name: pf_emulator
    shm_size: "2g"
    environment:
      - DEVICE=${DEVICE:-Pixel_6}
      - EMULATOR_PARAMS=${EMULATOR_PARAMS:--noaudio -gpu swiftshader_indirect}
      - WEB_VNC=true
    ports:
      - "${NOVNC_PORT:-6080}:6080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:6080 || exit 1"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12

  pf_droidflow:
    build:
      context: ./playflow
      dockerfile: Dockerfile
    container_name: pf_droidflow
    environment:
      - PLAYFLOW_PORT=${PLAYFLOW_PORT:-5000}
      - DEVICE_SERIAL=${DEVICE_SERIAL:-}
      - UPSTREAM_ADB=pf_emulator:5555
    volumes:
      - playflow_data:/var/lib/playflow
    ports:
      - "${PLAYFLOW_PORT:-5000}:5000"
    tmpfs:
      - /tmp
    depends_on:
      pf_emulator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      start_period: 180s
      interval: 15s
      timeout: 10s
      retries: 12